// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"maxblog-me-admin/internal/api"
	"maxblog-me-admin/internal/conf"
	"maxblog-me-admin/internal/core"
	"maxblog-me-admin/internal/middleware/interceptor"
	"maxblog-me-admin/src/handler"
	"maxblog-me-admin/src/service"
)

// Injectors from wire.go:

func InitInjector() (*Injector, error) {
	bData := &service.BData{}
	logger := &core.Logger{}
	response := &core.Response{
		ILogger: logger,
	}
	hData := &handler.HData{
		BData: bData,
		IRes:  response,
	}
	apiHandler := &api.Handler{
		HandlerData: hData,
	}
	engine := conf.InitGinEngine(apiHandler)
	interceptorInterceptor := &interceptor.Interceptor{}
	injector := &Injector{
		Engine:      engine,
		Handler:     apiHandler,
		Interceptor: interceptorInterceptor,
	}
	return injector, nil
}
