run_mode: "debug"
logger:
  color: true

app:
  app_name: "maxblog-me-admin"
  version: "0.1.0"

server:
  host: "127.0.0.1"
  port: 9201
  shutdown_timeout: 10
  tags:
    - maxblog-me-admin
    - maxblog

upstream:
  maxblog_fe_admin:
    host: "127.0.0.1"
    port: 9102

downstream:
  maxblog_be_demo:
    host: "127.0.0.1"
    port: 9304

redis:
  host: "127.0.0.1"
  port: 6379

consul:
  host: "127.0.0.1"
  port: 8500

