run_mode: "release"
logger:
  color: false

app:
  app_name: "maxblog-me-admin"
  version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 9201
  shutdown_timeout: 10
  tags:
    - maxblog-me-admin
    - maxblog

upstream:
  maxblog_fe_admin:
    host: "10.192.0.5"
    port: 9102

downstream:
  maxblog_be_user:
    host: "10.192.0.5"
    port: 9301
  maxblog_be_demo:
    host: "10.192.0.5"
    port: 9304

redis:
  host: "10.192.0.5"
  port: 6379

consul:
  host: "10.192.0.5"
  port: 8500

